### ISSUE TITLE
system hang when unbinding nvidia gpu

### ISSUE THREAD

**Issue by bohrasd** [hyphone/asus-g14-fedora#2]
I can't poweroff my g14 and it complains amdgpuboot service wont stop
When I tried the script step by step I found
`  echo -n "0000:01:00.0" > /sys/bus/pci/drivers/nvidia/unbind`
hanged

**Comment by marcolaux** [comment]
hmm, propably this is because of the last commit.
Could you checkout this state and see how it works for you?

git checkout 492f71975283e8a7372d5fbae91d6461169086fa

**Comment by marcolaux** [comment]
this script gets called on boot, not on shutdown

I haven't checked the latest changes from @tashiu
The previous states work just fine for me.

**Comment by bohrasd** [comment]
Im using exactly that configuration, and you're right it only happen on boot or switch.
I looked up this problem and someone suggest that I cant unbind the nvidia device when nvidia/nvidia_modeset/nvidia_uvm mod loaded. Is that real?

The poweroff issue now only happen when I close the lid too soon after I type poweroff, I think that's unrelated to this.

**Comment by marcolaux** [comment]
As long as the Nvidia is not in use it should work.

Do you use gdm as a display manager?

The script stops it before the Nvidia gets unbinded.

Do you use default fedora with gnome?

> I looked up this problem and someone suggest that I cant unbind the nvidia device when nvidia/nvidia_modeset/nvidia_uvm mod loaded. Is that real?

This is not true. You can always unbind it when the Nvidia is not in use (that's why the script stops GDM). You can't remove the "nvidia" driver (rmmod nvidia) when "nvidia_uvm" and "nvidia_modeset" are loaded. But I don't remove the nvidia driver, I just unbind the device from the driver.

**Comment by bohrasd** [comment]
I was using kde spin and I uninstalled kde package group and swtich to gdm/pantheon desktop after I noticed the script stops gdm.
I think I should try vanilla gnome.
Thanks for your patience

**Comment by marcolaux** [comment]
You of course could also just alter the script and stop the display manager of your choice (for example sddm).

Or if it doesn't work for your configuration I suggest not using the systemd services "asusgpuboot" and "asusgpuswitch" and use the switching method of "asusctl" wich requires a reboot.

**Comment by marcolaux** [comment]
And I suggest using Gnome Shell as in this repo here is a Shell extension that let's you switch your GPU just with a single click (just activate "amd nvidia switcher" in Twaks or Extensions.

**Comment by marcolaux** [comment]
I had the same problem with Ubuntu 20.10.

When adding `amdgpu.modeset=1 nvidia-drm.modeset=0` to `/etc/default/grub` as parameters to GRUB_CMDLINE_LINUX_DEFAULT and execute `update-grub2` it does not hang anymore.

**Comment by bohrasd** [comment]
I upgraded asus-nb-ctrl to 2.0 and use their integrated gfx control. 
Any plan to upgrade this project to 2.0? ;)

**Comment by marcolaux** [comment]
I'll look into it. I made this repo because with this method it's not needed to reboot between integrated and hybrid (also when using my GNOME Shell extension). So this is still relevant when you want to try this out.

If you are fine with rebooting I suggest using this nice tray application: https://github.com/Baldomo/asusctltray/
If you use GNOME Shell you then have to use an extension that displays legacy icons.

**Comment by mp3guy** [comment]
Same problem here, had to use the `amdgpu.modeset=1 nvidia-drm.modeset=0` solution. 

GA401IU-HE001T, fresh install of Fedora 32 and executed your instructions as listed in README.md. Kernel 5.9.11-100.fc32.x86_64.

**Comment by marcolaux** [comment]
Thanks for reporting, I'll update the readme then.
Personally I use https://github.com/Baldomo/asusctltray/ nowadays to switch.

**Comment by mp3guy** [comment]
Trying it out now, I hit the same issue you hit here, how did you fix it? https://github.com/Baldomo/asusctltray/issues/1

**Comment by marcolaux** [comment]
You should revert the kernel parameter changes and remove the modprobe files of this repo. This here and the normal asusctl method conflict with each other. Asusctl cannot control the GPU when you use the configurations here.

**Comment by marcolaux** [comment]
oh and enable gfx_managed in /etc/asusd/asusd.conf again

**Comment by marcolaux** [comment]
as I the current repo here does not use the unbinding method anymore but asusctl's method of switching I close this issue
