### ISSUE TITLE
Kernel update to 5.11

### ISSUE THREAD

**Issue by eugenov** [hyphone/asus-g14-fedora#6]
Hello!
I believe there is no need in some packages with release 5.11 kernel (dkms-hid-asus-rog i.e). Could you rescan your .md and remove obsolete things?
Also I am sure we have need in kernel update procedure with nvidia dkms-ing and such things. Almost every time updating kernel I do smth wrong, drivers broke, no gpu etc., so proper instructions needed.
Thank you!

**Comment by marcolaux** [comment]
Thanks for the suggestion.

I removed the not needed dkms modules.

I for myself don't need to do anything with Fedora after updates these days. The Nvidia modules that I describe here come from the rpmfusion repository and those update reliably.

When you do the updates via DNF be sure you wait a while before you reboot. There are still some processes going on that recompile some kernel modules after `dnf update` is completed.

I use fedora since the beginning of this year again and haven't had an issue since.

So I just hit `dnf update --refresh` when I'm in the mood of updating. When it's done I have a look in my activities monitor to see if anything is still working and consuming CPU time. For example rpmbuild will be seen there for some time.
When everything is done and idle again I reboot.

**Comment by eugenov** [comment]
And one more point - readme.md items # are 1, 2, 3, 4, 5, 6, then 5 and 6 again, just typos
